version: "3"

services:
  postgres:
    image: postgres
    container_name: py-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: py
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - py-network
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local

networks:
  py-network:
    driver: bridge
